import {build} from 'esbuild';
import {mkdirSync} from 'node:fs';
mkdirSync('qa',{recursive:true});
import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
await build({entryPoints:['tests/browser/provider.js'],outfile:'qa/privacy-provider-bundle.js',bundle:true,format:'iife',platform:'browser',inject:['src/polyfill.js']});
const b=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE||undefined,headless:true});
try{const p=await b.newPage();await p.addInitScript({path:'qa/privacy-provider-bundle.js'});let release,held=false,hold=false,mutations=0;const config={withdraw_fee_rate:.0035,withdraw_rent_fee:.006,rent_fees:{usdc:.7,usdt:.9},minimum_withdrawal:{sol:.01,usdc:2,usdt:3}};
await p.route('https://api3.privacycash.org/**',async route=>{if(route.request().method()!=='GET'){mutations++;await route.abort();return;}if(route.request().url().endsWith('/config')){if(hold){held=true;await new Promise(r=>release=r);hold=false;}await route.fulfill({json:config});return;}if(route.request().url().includes('/utxos/range')){await route.fulfill({json:{encrypted_outputs:[],hasMore:false,total:0}});return;}await route.abort();});
await p.route('https://solana-rpc.publicnode.com/**',async route=>{const req=route.request().postDataJSON();let result;if(req.method==='getGenesisHash')result='5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d';else if(req.method==='getBalance')result={context:{slot:1},value:2000000000};else if(req.method==='getAccountInfo')result={context:{slot:1},value:req.params[0]==='9fhQBbumKEFuXtMBDw8AaQyAjCorLGJQiS3skWZdQyQD'?{data:['','base64'],executable:true,owner:'11111111111111111111111111111111',lamports:1,rentEpoch:0}:null};else throw Error('Unexpected RPC '+req.method);await route.fulfill({json:{jsonrpc:'2.0',id:req.id,result}})});
await p.goto('http://127.0.0.1:4173/wallet/');await p.locator('#software-wallet').check();await p.evaluate(()=>window.rejectUnlock=true);await p.locator('#unlock').click();await p.waitForFunction(()=>!document.querySelector('#unlock').disabled);assert.equal(await p.locator('#unlock-state').textContent(),'LOCKED');assert.match(await p.locator('#privacy-status').textContent(),/declined/i);await p.evaluate(()=>window.rejectUnlock=false);await p.locator('#unlock').click();await p.waitForFunction(()=>!document.querySelector('#unlock').disabled);assert.equal(await p.locator('#unlock-state').textContent(),'UNLOCKED');
await p.locator('#sync').click();await p.waitForFunction(()=>!document.querySelector('#sync').disabled);assert.equal(await p.locator('#private-0').textContent(),'0');await p.locator('#hide-balances').click();assert.match(await p.locator('#private-0').textContent(),/•/);await p.locator('#hide-balances').click();assert.equal(await p.locator('#private-0').textContent(),'0');
await p.locator('#amount').fill('0.1');hold=true;await p.locator('#review-payment').click();while(!held)await new Promise(r=>setTimeout(r,10));await p.locator('#amount').fill('0.2');release();await p.waitForFunction(()=>!document.querySelector('#review-payment').disabled);assert.equal(await p.locator('#payment-review').isVisible(),false);assert.match(await p.locator('#privacy-status').textContent(),/changed during review/);
await p.locator('#review-payment').click();await p.locator('#payment-review').waitFor();await p.locator('#acknowledge').check();held=false;hold=true;await p.locator('#confirm-payment').click();while(!held)await new Promise(r=>setTimeout(r,10));await p.locator('#cancel-review').click();release();await p.waitForFunction(()=>!document.querySelector('#confirm-payment').disabled);assert.match(await p.locator('#privacy-status').textContent(),/details changed/);assert.equal(mutations,0);assert.equal(await p.evaluate(()=>window.fixtureTxSigns||0),0);
await p.evaluate(()=>window.fixtureAccountChange());assert.equal(await p.locator('#unlock-state').textContent(),'LOCKED');assert.equal(await p.locator('#private-0').textContent(),'—');await p.locator('#unlock').click();await p.waitForFunction(()=>!document.querySelector('#unlock').disabled);await p.locator('#provider').selectOption('solflare');assert.equal(await p.locator('#unlock-state').textContent(),'LOCKED');console.log('PASS rejected signature, deterministic unlock, balance privacy, edit-during-review, cancel-during-confirm, account change and provider change. Zero submissions.');
}finally{await b.close()}
