import {mkdirSync} from 'node:fs';
mkdirSync('qa',{recursive:true});
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import {build} from 'esbuild';
import {Keypair} from '@solana/web3.js';
import assert from 'node:assert/strict';
import bs58 from 'bs58';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
await build({entryPoints:['tests/browser/notes-fixture.js'],outfile:'qa/privacy-notes-bundle.js',bundle:true,format:'iife',platform:'browser',inject:['src/privacy-polyfill.js'],alias:{crypto:'crypto-browserify',stream:'stream-browserify',util:'util',assert:'assert'},define:{global:'globalThis','process.env':'{}'},drop:['console']});
const spl=process.env.AUDIT_ASSET==='USDC',mint='EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v';
await build({entryPoints:['tests/browser/provider.js'],outfile:'qa/privacy-provider-bundle.js',bundle:true,format:'iife',platform:'browser',inject:['src/polyfill.js']});
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE||undefined,headless:true});
try{const page=await browser.newPage();await page.addInitScript(()=>window.__auditSeed=Array.from({length:32},(_,i)=>i+1));await page.addInitScript({path:'qa/privacy-provider-bundle.js'});let fixture=null,submitted=0,body,mismatch=false;
 await page.route(url=>url.hostname==='api3.privacycash.org',async route=>{const req=route.request(),url=new URL(req.url());
  if(req.method()!=='GET'){if(url.pathname==='/utxos/indices'){await route.fulfill({json:{indices:req.postDataJSON().encrypted_outputs.map(()=>0)}});return;}if(url.pathname===(spl?'/withdraw/spl':'/withdraw')){submitted++;body=req.postDataJSON();await route.fulfill({json:{success:true,signature:'3'.repeat(88)}});return;}await route.abort();throw new Error('Blocked unexpected write');}
  if(url.pathname==='/utxos/range'){await route.fulfill({json:{encrypted_outputs:Number(url.searchParams.get('start'))===0?[fixture.encrypted]:[],hasMore:false,total:1}});return;}
  if(url.pathname.includes('/merkle/proofv2/')){await route.fulfill({json:{root:fixture.root,nextIndex:2,proofs:[fixture.path,{pathElements:Array(26).fill('0'),pathIndices:Array(26).fill(0)}]}});return;}
  if(url.pathname.includes('/utxos/check/')){await route.fulfill({json:{exists:true}});return;}await route.continue();
 });
 await page.route(url=>url.hostname==='solana-rpc.publicnode.com',async route=>{const req=route.request().postDataJSON();if(req.method==='sendTransaction'){await route.abort();throw new Error('Network write blocked');}if(req.method==='getTransaction'){await route.fulfill({json:{jsonrpc:'2.0',id:req.id,result:{slot:100,blockTime:1,meta:{err:null,fee:5000,preBalances:[0],postBalances:[0]},transaction:{signatures:['3'.repeat(88)],message:{header:{numRequiredSignatures:0,numReadonlySignedAccounts:0,numReadonlyUnsignedAccounts:1},accountKeys:['9fhQBbumKEFuXtMBDw8AaQyAjCorLGJQiS3skWZdQyQD'],recentBlockhash:'1'.repeat(32),instructions:[{programIdIndex:0,accounts:[],data:bs58.encode(Buffer.from(mismatch?'AAAA':body.serializedProof,'base64'))}]}},version:'legacy'}}});return;}if(req.method==='getSignatureStatuses'){await route.fulfill({json:{jsonrpc:'2.0',id:req.id,result:{context:{slot:100},value:[{slot:100,err:null,confirmations:null,confirmationStatus:'finalized'}]}}});return;}await route.continue();});
 await page.goto('http://127.0.0.1:4173/wallet/');await page.addScriptTag({content:await readFile('qa/privacy-notes-bundle.js','utf8')});fixture=await page.evaluate(({spl,mint})=>window.makePrivateNote(spl?{mint,amount:'10000000'}:{}),{spl,mint});if(spl)await page.locator('#asset').selectOption('1');
 await page.locator('#software-wallet').check();await page.locator('#unlock').click();await page.waitForFunction(()=>!document.getElementById('unlock').disabled,{},{timeout:60000});
 const recoveredOwner=await page.locator('#owner').textContent();await page.reload();if(spl)await page.locator('#asset').selectOption('1');await page.locator('#software-wallet').check();await page.locator('#unlock').click();await page.waitForFunction(()=>!document.getElementById('unlock').disabled,{},{timeout:60000});assert.equal(await page.locator('#owner').textContent(),recoveredOwner);console.log('Reload recovery: same wallet and encryption fingerprint');await page.locator('#operation').selectOption('withdraw');const recipient=Keypair.generate().publicKey.toBase58();await page.locator('#recipient').fill(recipient);await page.locator('#amount').fill(spl?'5':'0.1');await page.locator('#review-payment').click();await page.waitForFunction(()=>!document.getElementById('review-payment').disabled,{},{timeout:60000});console.log('Review:',await page.locator('#privacy-status').textContent());assert.equal(await page.locator('#payment-review').isVisible(),true);assert.equal(await page.locator(spl?'#private-1':'#private-0').textContent(),spl?'10':'1');await page.locator('#acknowledge').check();await page.locator('#confirm-payment').click();await page.waitForFunction(()=>!document.getElementById('confirm-payment').disabled,{},{timeout:180000});console.log('Withdrawal:',await page.locator('#privacy-status').textContent());assert.equal(await page.locator('#tx-state').textContent(),'Finalized');assert.equal(submitted,1);assert.equal(body.recipient,recipient);assert.equal(-body.extAmount+body.fee,spl?5000000:100000000);assert.equal(await page.evaluate(()=>window.fixtureTxSigns||0),0);
 mismatch=true;await page.locator('#check-status').click();await page.waitForFunction(()=>!document.getElementById('check-status').disabled);assert.match(await page.locator('#tx-state').textContent(),/Proof mismatch/);console.log('Wrong returned transaction proof rejected');
 console.log('PASS: actual browser AES authenticated encryption/tamper rejection, note scanning/decryption, private balance, withdrawal proof construction and exact reviewed relay payload. Submission/finality were fixtures; no network transfer.');
}finally{await browser.close();}

